name: directpipe

services:
  coturn:
    image: coturn/coturn:latest
    ports:
      - '3478:3478/udp'
      - '3478:3478/tcp'
      - '49152-49252:49152-49252/udp'
    command: >
      -n
      --fingerprint
      --use-auth-secret
      --static-auth-secret=${TURN_SECRET}
      --realm=${TURN_REALM}
      --total-quota=100
      --stale-nonce=600
      --no-tls
      --no-dtls
      --min-port=49152
      --max-port=49252
      --no-multicast-peers
      --no-cli
    env_file:
      - ./envs/shared.env
      - ./envs/api.env
    networks:
      - app
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - '127.0.0.1:4000:4000'
    env_file:
      - ./envs/shared.env
      - ./envs/api.env
    depends_on:
      - coturn
    networks:
      - app
      - proxy
    restart: unless-stopped

  app:
    build:
      context: ./app
      args:
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - '127.0.0.1:3002:3000'
    env_file:
      - ./envs/shared.env
      - ./envs/app.env
    depends_on:
      - api
    networks:
      - app
      - proxy
    restart: unless-stopped

networks:
  app:
    driver: bridge
  proxy:
    external: true
    name: ${PROXY_NETWORK:-npm_proxy}
